config:
  selfUrl: # https://test3-st-product
  corsOrigins: #
  connectionStrings:
    productService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://test3-st-authserver
    requireHttpsMetadata: # "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: test3-st-product
  tlsSecret: test3-tls

image:
  repository: mycompanyname/test3-service-product
  tag: latest
  pullPolicy: IfNotPresent

env: {}      