config:
  selfUrl: https://test5-st-saas
  corsOrigins: https://test5-st-gateway-web,https://test5-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://test5-st-authserver
    requireHttpsMetadata: # "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: test5-st-saas
  tlsSecret: test5-tls

image:
  repository: mycompanyname/test5-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      