config:
  selfUrl: # https://test3-st-identity
  corsOrigins: # https://test3-st-gateway-web,https://test3-st-gateway-public-web
  connectionStrings:
    identityService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://test3-st-authserver
    requireHttpsMetadata: # "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

# Seeded applications and resources 
openIdDict:
  applications:
    authServerRootUrl: #
    angularRootUrl: #
    webRootUrl: #
    blazorRootUrl: #
    blazorServerRootUrl: #
    publicWebRootUrl: #
    webGatewayRootUrl: #
    publicWebGatewayRootUrl: #
  resources:  
    accountServiceRootUrl: #
    administrationServiceRootUrl: #
    identityServiceRootUrl: #
    saasServiceRootUrl: #
    productServiceRootUrl: #

ingress:
  host: test3-st-identity
  tlsSecret: test3-tls

image:
  repository: mycompanyname/test3-service-identity
  tag: latest
  pullPolicy: IfNotPresent

env: {}
