config:
  selfUrl: # 
  gatewayUrl: # 
  authServer:
      authority: # http://test5-st-authserver
      responseType: "code"

ingress:
  host: # test5-st-blazor
  tlsSecret: test5-tls

image:
  repository: mycompanyname/test5-app-blazor
  tag: latest
  pullPolicy: IfNotPresent

env: {}