config:
  selfUrl: # https://test_2-st-product
  corsOrigins: #
  connectionStrings:
    productService: #
    administrationService: #
    saasService: #
  authServer:
    authority: # http://test_2-st-authserver
    requireHttpsMetadata: # "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: test_2-st-product
  tlsSecret: test_2-tls

image:
  repository: mycompanyname/test_2-service-product
  tag: latest
  pullPolicy: IfNotPresent

env: {}      