config:
  selfUrl: # 
  gatewayUrl: # 
  authServer:
      authority: # http://test3-st-authserver
      responseType: "code"

ingress:
  host: # test3-st-blazor
  tlsSecret: test3-tls

image:
  repository: mycompanyname/test3-app-blazor
  tag: latest
  pullPolicy: IfNotPresent

env: {}