// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Chat.Settings;

// ReSharper disable once CheckNamespace
namespace Volo.Chat.Settings.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISettingsAppService), typeof(SettingsClientProxy))]
public partial class SettingsClientProxy : ClientProxyBase<ISettingsAppService>, ISettingsAppService
{
    public virtual async Task SetSendOnEnterSettingAsync(SendOnEnterSettingDto input)
    {
        await RequestAsync(nameof(SetSendOnEnterSettingAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SendOnEnterSettingDto), input }
        });
    }
}
