config:
  selfUrl: # https://test_2-st-administration
  corsOrigins: # https://test_2-st-gateway-web,https://test_2-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://test_2-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
  remoteServices:
    abpIdentityBaseUrl: #
    useCurrentToken: "false"
  dotnetEnv: #
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

synchedCommunication:
  authority: # https://test_2-st-authserver
  requireHttps: #
  validateIssuerName: #
  validateEndpoints: #

ingress:
  host: # test_2-st-administration
  tlsSecret: test_2-tls

image:
  repository: mycompanyname/test_2-service-administration
  tag: latest
  pullPolicy: IfNotPresent

env: {}
