config:
  selfUrl: # 
  gatewayUrl: # 
  authServer:
      authority: # http://test4-st-authserver
      requireHttpsMetadata: # false
      responseType: "code"
      strictDiscoveryDocumentValidation: false
      skipIssuerCheck: true

ingress:
  host: # test4-st-angular
  tlsSecret: test4-tls

image:
  repository: mycompanyname/test4-app-angular
  tag: latest
  pullPolicy: IfNotPresent

env: {}